# playbook to install mongodb in database VM
---

# where to install the db
- hosts: db

  gather_facts: yes

  become: true

  tasks:

  # download the key
  - name: Import the MongoDB public key
    ansible.builtin.apt_key:
      url: https://www.mongodb.org/static/pgp/server-7.0.asc
      state: present

  # Add mongodb repo
  - name: Add the MongoDB repository
    ansible.builtin.apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
      state: present
      update_cache: yes

  # install mongodb
  - name: Install MongoDB 7.0.6
    ansible.builtin.apt:
      name: mongodb-org=7.0.6
      state: present
      update_cache: yes

  # Enable mongodb
  - name: Ensure MongoDB is enabled and started
    ansible.builtin.systemd:
      name: mongod
      enabled: yes
      state: started







